# Base configs
baseurl:
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kalle"
subtitle: "See the world through my eyes!"
author: "Kalle"
header:
 title: "Photography"
 subtitle: "by me"
