# Base configs
baseurl: "https://koodikulis.github.io/photography/index.html"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kalle"
subtitle: "Näe"
author: "Kalle"
header:
 title: "Photography"
 subtitle: "Kalle"
footer:
 name: "Hei"
 bio: "Hei"
 github: ""
 
web_design: ""
social_urls:
 
  instagram: "https://www.instagram.com/ram_patra"

  github: "https://www.github.com/rampatra"