# Base configs
baseurl: "https://koodikulis.github.io/photography/index.html"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Kalle Ketola"
subtitle: "Valoa ja kuvia"
author: "Kalle Ketola"
header:
 title: "Photography"
 subtitle: "Kalle"
footer:
 name: "Kalle Ketola"
 bio: "Lost in Finland"
 github: ""
 
web_design: ""
social_urls:
 
  instagram: "https://www.instagram.com/winterbridgevalley/"

  github: "https://www.github.com/koodikulis