# Base configs
baseurl:https://koodikulis.github.io/photography/index.html
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: Hei
subtitle:Hei 
author: Hei
header:Hei
 title: Hei
 subtitle: Hei
footer:Hei
 name: 
 bio: 
 github: 
web_design: 
social_urls:
  facebook: 
  twitter: 
  instagram: 
  dribbble: 
  linkedin: 
  github: 
