# Base configs
baseurl: "https://koodikulis.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Kalle Ketola"
subtitle: "Valoa ja kuvia"
author: "Kalle Ketola"
header:
 title: "Photography"
 subtitle: "Kalle"
footer:
 name: "Kalle Ketola"
 bio: "Lost in Finland"
 github: ""
 
web_design: ""
social_urls:
  facebook: ""
  twitter: ""
  instagram: "https://www.instagram.com/winterbridgevalley/"
  dribbble: ""
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/koodikulis"
