# Base configs
baseurl: "https://kalleketola.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"


# UI configs
title: "Kalle Ketola"
subtitle: "Help, I'm trapped inside this camera."
author: "Kalle Ketola"
header:
 title: "Help, I'm trapped inside this camera."
 subtitle: "Kalle Ketola"
footer:
 name: "Kalle Ketola"
 bio: "Send a postcards to ketola.kalle at gmail.com"
 github: "https://www.github.com/kalleketola"
 web_design:
 
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/kalle.ketola"
  instagram: "https://www.instagram.com/winterbridgevalley/"
  github: "https://www.github.com/kalleketola"
