# Base configs
baseurl: "https://koodikulis.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
image_fulls_loc_air: "/images/airfull"
image_thumbs_loc_air: "/images/airthumb"
image_fulls_loc_land: "/images/landfull"
image_thumbs_loc_land: "/images/landthumb"
image_fulls_loc_livingthings: "/images/livingthings"
image_thumbs_loc_livingthing: "/images/livingthumb"


# UI configs
title: "Kalle Ketola"
subtitle: "Help, I'm trapped inside this camera."
author: "Kalle Ketola"
header:
 title: "Help, I'm trapped inside this camera."
 subtitle: "Kalle Ketola"
 subtitle2: "Air / "
 subtitle3: "Land / "
 subtitle4: "Living Things /"
footer:
 name: "Kalle Ketola"
 bio: "Lost in Finland"
 github: "https://www.github.com/koodikulis"
 
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/kalle.ketola"
  twitter: ""
  instagram: "https://www.instagram.com/winterbridgevalley/"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/koodikulis"
