# Base configs
baseurl: 
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Valokuvia Kalle Ketola"
subtitle: "Valoa ja kuvia"
author: "Kalle Ketola"
header:
 title: "Valokuvia"
 subtitle: "Kalle Ketola"
footer:
 # name: "Hei olen Kalle"
 bio: "Lost in Finland."
social_urls:
  
  instagram: "https://www.instagram.com/winterbridgevalley/"
  github: "https://www.github.com/koodikulis"
